import { safeUrl, verifiedProjects as verifiedRecords, filterProjects, starsText } from './model.js';
const $ = (id) => document.getElementById(id);
const STORAGE_KEY = 'three-field-saved-v1';
let dataset = { metadata: {}, projects: [] };
let bookmarks = new Set();
try { const stored = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'); if (Array.isArray(stored)) bookmarks = new Set(stored.filter(x => typeof x === 'string')); } catch {}
const params = new URLSearchParams(location.search);
const state = { query: params.get('q') || '', category: params.get('category') || 'all', sort: params.get('sort') || 'curated', saved: params.get('saved') === '1' };
if (!['curated', 'stars', 'name'].includes(state.sort)) state.sort = 'curated';
const palette = [['#e1e8d5','#657346'],['#f1ceb6','#995738'],['#dbe4e8','#426377'],['#ddd9ed','#665984'],['#dde9e5','#477867'],['#e7dfc4','#877641']];
function node(tag, className, text) { const el = document.createElement(tag); if (className) el.className = className; if (text !== undefined) el.textContent = text; return el; }
function link(text, url, className) { const el = node('a', className, text); const safe = safeUrl(url); if (safe) { el.href = safe; el.target = '_blank'; el.rel = 'noopener noreferrer'; } return el; }
function verifiedProjects() { return verifiedRecords(dataset.projects); }
function sourceLabel(p) { return p.origin === 'facebook' ? 'FACEBOOK 來源追溯' : '獨立查核補充 · 非 Facebook 來源'; }
function updateUrl() { const p = new URLSearchParams(); if (state.query) p.set('q', state.query); if (state.category !== 'all') p.set('category', state.category); if (state.sort !== 'curated') p.set('sort', state.sort); if (state.saved) p.set('saved', '1'); history.replaceState(null, '', location.pathname + (p.size ? '?' + p : '') + location.hash); }
function filteredProjects() { return filterProjects(dataset.projects, state, bookmarks); }
function renderChips() { const categories = [...new Set(verifiedProjects().map(p=>p.category))]; if(state.category !== 'all' && !categories.includes(state.category)) state.category='all'; $('categories').replaceChildren(); for(const category of ['all',...categories]) { const b=node('button','chip',category==='all'?'全部專案':category); b.type='button'; b.setAttribute('aria-pressed',String(state.category===category)); b.addEventListener('click',()=>{state.category=category;render();}); $('categories').append(b); } }
function toggleBookmark(project) { if(bookmarks.has(project.id)) bookmarks.delete(project.id); else bookmarks.add(project.id); try { localStorage.setItem(STORAGE_KEY,JSON.stringify([...bookmarks])); } catch {} render(); }
function card(project,index) { const el=node('article','card'); const art=node('div','card-art'); const colors=palette[index%palette.length]; art.style.setProperty('--card-bg',colors[0]); art.style.setProperty('--card-ink',colors[1]); const shape=node('div','art-shape'); shape.setAttribute('aria-hidden','true'); art.append(shape); art.append(node('span','art-label','CODE / PLAY / DISCOVER')); const save=node('button','bookmark',bookmarks.has(project.id)?'♥':'♡'); save.type='button'; save.setAttribute('aria-label',(bookmarks.has(project.id)?'取消收藏 ':'收藏 ')+project.name); save.setAttribute('aria-pressed',String(bookmarks.has(project.id))); save.addEventListener('click',()=>toggleBookmark(project)); art.append(save); const body=node('div','card-body'); const meta=node('div','card-meta'); meta.append(node('span','category-name',project.category),node('span','license-badge',project.license.name)); body.append(meta,node('h3','',project.name),node('p','card-description',project.summary)); const tags=node('div','tags'); for(const tag of project.tags||[]) tags.append(node('span','tag',tag)); body.append(tags); if(project.license.scopeNote)body.append(node('p','asset-warning',project.license.scopeNote)); const bottom=node('div','card-bottom'); const star=node('span','stars',starsText(project)); if(project.popularity?.observedAt) star.title='GitHub 星數查核日：'+project.popularity.observedAt+'（UTC）'; const details=node('button','detail-button','探索專案 ↗'); details.type='button'; details.setAttribute('aria-label','探索 '+project.name); details.addEventListener('click',()=>openProject(project)); bottom.append(star,details); body.append(bottom,node('p','card-origin',sourceLabel(project))); el.append(art,body); return el; }
function render() { renderChips(); const projects=filteredProjects(); $('project-grid').replaceChildren(...projects.map(card)); $('result-count').textContent=`顯示 ${projects.length} / ${verifiedProjects().length} 個專案`; $('saved-count').textContent=String(verifiedProjects().filter(p=>bookmarks.has(p.id)).length); $('saved-filter').setAttribute('aria-pressed',String(state.saved)); $('empty-state').hidden=projects.length!==0; const noData=verifiedProjects().length===0; $('empty-title').textContent=noData?'來源查核完成後，從這裡開始探索。':'這個條件還沒有找到專案。'; $('empty-description').textContent=noData?'目前尚未完成指定來源的專案查核，因此不以其他清單或示意卡片代替來源內容。':'試試不同關鍵字、其他分類，或清除篩選條件。'; $('reset-filters').hidden=noData; updateUrl(); }
function addDetail(list,label,value){ list.append(node('dt','',label)); const dd=node('dd'); if(value instanceof Node)dd.append(value); else dd.textContent=value; list.append(dd); }
function openProject(p) { const content=$('dialog-content'); const heading=node('h2','',p.name); heading.id='dialog-title'; const links=node('div','dialog-links'); if(safeUrl(p.demoUrl))links.append(link('官方展示 ↗',p.demoUrl)); links.append(link('程式碼 ↗',p.repositoryUrl),link('授權原文 ↗',p.license.url)); const list=node('dl','detail-list'); addDetail(list,'開源授權',p.license.name+' · 已查核'); addDetail(list,'人氣紀錄',starsText(p)+(p.popularity?.observedAt?' · 查核於 '+p.popularity.observedAt+'（UTC）':'')); if(safeUrl(p.popularity?.sourceUrl))addDetail(list,'星數依據',link('GitHub API 快照來源 ↗',p.popularity.sourceUrl)); addDetail(list,'收錄來源',sourceLabel(p)); const sources=node('ul'); for(const [index,source] of (p.sources||[]).entries()) { if(!safeUrl(source.url))continue; const li=node('li');li.append(link(source.label||`來源 ${index+1}`,source.url));sources.append(li); } addDetail(list,'來源連結',sources.childElementCount?sources:'未提供可公開的來源連結'); if(p.sourceDateLabel)addDetail(list,'貼文日期標籤',p.sourceDateLabel+'（依 Facebook 原顯示，未推定年份）'); if(p.verifiedAt)addDetail(list,'查核日期',p.verifiedAt+'（UTC）'); if(p.notes?.length)addDetail(list,'補充說明',Array.isArray(p.notes)?p.notes.join(' '):p.notes); content.replaceChildren(node('p','dialog-category',p.category),heading,node('p','dialog-summary',p.details||p.summary),links,list,node('p','detail-note','星數是特定時間的觀察值，不是全球排名。授權範圍以儲存庫原文為準，展示中的素材可能另有權利限制。')); $('project-dialog').showModal(); }

function renderTracking() {
  const other = dataset.otherSourceResults || [];
  $('other-results-count').textContent = `（${other.reduce((sum,p)=>sum+(p.copiesObserved||1),0)} 則）`;
  $('other-results-list').replaceChildren();
  for(const p of other){const row=node('article','other-result');row.append(node('h3','',p.topic+(p.copiesObserved>1?` · ${p.copiesObserved} 則重複`:'')),node('p','',p.status));const links=node('div','other-result-links');for(const [i,url]of(p.sourceUrls||[]).entries())if(safeUrl(url))links.append(link(`來源 ${i+1} ↗`,url));row.append(links);if(p.sourceLimit)row.append(node('p','',p.sourceLimit));$('other-results-list').append(row);}

  const records = dataset.excludedProjects || [];
  $('source-tracking').hidden = records.length === 0;
  $('tracking-list').replaceChildren();
  for (const p of records) {
    const item = node('article', 'tracking-item');
    const copy = node('div', 'tracking-copy');
    copy.append(node('span', 'tracking-status', p.license?.name || '開源狀態未確認'), node('h3', '', p.name), node('p', '', p.summary));
    if(p.notes?.length) copy.append(node('p', 'tracking-notes', Array.isArray(p.notes) ? p.notes.join(' ') : p.notes));
    if(p.popularity?.observedAt) copy.append(node('p','tracking-notes',starsText(p)+' · '+p.popularity.observedAt+'（UTC）'));
    const links=node('div','tracking-links');
    if(safeUrl(p.repositoryUrl)) links.append(link('公開儲存庫 ↗',p.repositoryUrl));
    if(safeUrl(p.demoUrl)) links.append(link('官方展示 ↗',p.demoUrl));
    const sources=(p.sources||[]).filter(s=>safeUrl(s.url)&&/(^|\.)facebook\.com$/.test(new URL(s.url).hostname));
    sources.forEach((source,index)=>links.append(link(sources.length>1?`來源貼文 ${index+1} ↗`:'來源貼文 ↗',source.url)));
    for(const source of p.sources||[])if(/授權/.test(source.label)&&safeUrl(source.url))links.append(link(source.label+' ↗',source.url));
    item.append(copy,links);$('tracking-list').append(item);
  }
}
$('search').value=state.query; $('sort').value=state.sort;
$('search').addEventListener('input',e=>{state.query=e.target.value;render();}); $('sort').addEventListener('change',e=>{state.sort=e.target.value;render();}); $('saved-filter').addEventListener('click',()=>{state.saved=!state.saved;render();}); $('reset-filters').addEventListener('click',()=>{state.query='';state.category='all';state.saved=false;$('search').value='';render();}); $('close-dialog').addEventListener('click',()=>$('project-dialog').close()); $('project-dialog').addEventListener('click',e=>{if(e.target===$('project-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)&&!$('project-dialog').open){e.preventDefault();$('search').focus();}});
try { const response=await fetch(new URL('data.json',import.meta.url)); if(!response.ok)throw new Error('HTTP '+response.status); dataset=await response.json(); if(!Array.isArray(dataset.projects)||!dataset.metadata)throw new Error('Invalid dataset'); const m=dataset.metadata; const ready=m.status==='complete'||m.status==='partial'; $('project-count').textContent=String(verifiedProjects().length).padStart(2,'0'); $('source-count').textContent=String(m.sourcePostCount||0).padStart(2,'0'); $('category-count').textContent=String(new Set(verifiedProjects().map(p=>p.category)).size).padStart(2,'0'); $('verified-date').textContent=m.checkedAt?m.checkedAt+' UTC':'等待來源查核'; $('coverage-alert').textContent=ready?(m.coverageSummary||'此目錄依可取得的來源整理；完整範圍與限制請見下方收錄方法。'):'整理中 · '+m.coverageDescription; $('coverage-alert').classList.toggle('ready',ready); $('coverage-description').textContent=m.coverageDescription; $('limitations').textContent='收錄限制：'+(m.limitations||[]).join(' '); if(safeUrl(m.sourceUrl))$('source-link').href=m.sourceUrl; renderTracking(); render(); } catch(error) { $('coverage-alert').textContent='資料暫時無法載入。請重新整理，或下載 JSON 資料檔查看；此狀態不代表來源中沒有專案。'; $('project-count').textContent='—';$('source-count').textContent='—';$('category-count').textContent='—';$('empty-state').hidden=false;$('empty-title').textContent='資料載入未完成';$('empty-description').textContent='若問題持續發生，請檢查網站資料檔是否可存取。';$('reset-filters').hidden=true;console.error('Directory data load failed:',error); }
