import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const data=JSON.parse(fs.readFileSync(path.join(root,'data.json'),'utf8'));
const url=u=>{try{return ['https:','http:'].includes(new URL(u).protocol);}catch{return false;}};
assert.equal(data.schemaVersion,1);assert.ok(data.metadata);assert.ok(Array.isArray(data.projects));assert.ok(url(data.metadata.sourceUrl));assert.ok(Number.isInteger(data.metadata.sourcePostCount));
const ids=new Set();for(const p of data.projects){assert.ok(p.id&&!ids.has(p.id),'Unique id required');ids.add(p.id);for(const k of ['name','summary','category'])assert.ok(typeof p[k]==='string'&&p[k].length,`${p.id}: ${k}`);assert.ok(['facebook','supplemental'].includes(p.origin));assert.ok(p.openSourceVerified===true&&p.license.verified===true);assert.ok(p.license.name&&url(p.license.url));assert.ok(url(p.repositoryUrl));assert.ok(!p.demoUrl||url(p.demoUrl));assert.ok(Array.isArray(p.sources)&&p.sources.length);for(const source of p.sources)assert.ok(url(source.url));if(p.origin==='facebook')assert.ok(p.sources.some(s=>new URL(s.url).hostname.match(/(^|\.)facebook\.com$/)),'Facebook source link required');if(p.popularity?.githubStars!=null){assert.ok(Number.isInteger(p.popularity.githubStars)&&p.popularity.githubStars>=0);assert.match(p.popularity.observedAt,/^\d{4}-\d{2}-\d{2}/);}assert.match(p.verifiedAt,/^\d{4}-\d{2}-\d{2}/);}
for (const p of data.excludedProjects || []) { assert.ok(p.openSourceVerified === false, 'Unverified items must not claim open source'); assert.ok(p.id && p.name && p.summary); assert.ok(!ids.has(p.id), 'Excluded item must not also appear in verified list'); for(const source of p.sources || []) assert.ok(url(source.url)); }
for(const f of ['index.html','styles.css','app.js','model.js'])assert.ok(fs.statSync(path.join(root,f)).size>0);
if(process.argv.includes('--publish')){assert.ok(['complete','partial'].includes(data.metadata.status),'Publication blocked: source collection not finalized');assert.ok(data.metadata.sourcePostCount>0,'Publication blocked: zero source posts');assert.ok(data.projects.some(p=>p.origin==='facebook'),'Publication blocked: no source-derived project');assert.ok(data.metadata.checkedAt);assert.equal(data.metadata.sourcePostCount,data.metadata.repositoryLinkedPosts+data.metadata.otherPosts);assert.equal(data.metadata.repositoryLinkedPosts,data.metadata.uniqueRepositoryLeads+data.metadata.duplicateRepositoryPosts);assert.equal(data.projects.length+(data.excludedProjects||[]).length,data.metadata.uniqueRepositoryLeads);const links=new Set([...data.projects,...(data.excludedProjects||[])].flatMap(p=>p.sources.filter(s=>/(^|\.)facebook\.com$/.test(new URL(s.url).hostname)).map(s=>s.url)));assert.equal(links.size,data.metadata.repositoryLinkedPosts,'Every repository-linked source post must be retained');assert.equal((data.otherSourceResults||[]).reduce((sum,p)=>sum+p.copiesObserved,0),data.metadata.otherPosts);}
console.log(`PASS: ${data.projects.length} project records; status ${data.metadata.status}${process.argv.includes('--publish')?'; publication data gate passed':''}`);
